import { createIcons, icons } from 'https://cdn.jsdelivr.net/npm/lucide@latest/+esm';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const SUPABASE_URL = window.DECALDEN_SUPABASE_URL;
const SUPABASE_KEY = window.DECALDEN_SUPABASE_KEY;
const supabase = (SUPABASE_URL && SUPABASE_KEY) ? createClient(SUPABASE_URL, SUPABASE_KEY) : null;

const STUDIO_EMAIL = 'xdecalden@gmail.com';

/* ---------------- Vinyl catalog ---------------- */
let VINYLS = [];

async function loadCatalog(){
  const response = await fetch('/api/catalog', { headers: { Accept: 'application/json' } });
  if(!response.ok) throw new Error('Catalog unavailable');
  const result = await response.json();
  VINYLS = (result.items || []).map(item => ({
    id: item.id,
    name: item.name,
    desc: item.description,
    icon: item.icon || 'sparkles',
    price: Number(item.price_per_sq_in),
    hasColor: !!item.has_color,
    specialOrder: !!item.special_order,
    colors: Array.isArray(item.colors) ? item.colors : [],
  }));
  if(!VINYLS.length) throw new Error('Catalog is empty');
}

const SHAPES = [
  { id:'contour', name:'Contour cut', mult:1.0 },
  { id:'square', name:'Square', mult:0.92 },
  { id:'circle', name:'Circle', mult:0.96 },
  { id:'rounded', name:'Rounded', mult:0.94 },
];
const SHIPPING = [
  { id:'free_us', name:'Domestic (USA)', detail:'Standard, no tracking', cost:0, region:'USA', icon:'home' },
  { id:'track_us', name:'Domestic + Tracking', detail:'Tracked USA delivery', cost:5, region:'USA', icon:'map-pin' },
  { id:'free_intl', name:'International', detail:'Standard, no tracking', cost:0, region:'International', icon:'globe' },
  { id:'track_intl', name:'International + Tracking', detail:'Tracked worldwide', cost:10, region:'International', icon:'plane' },
];
const state = { file:null, imgName:null, imageEl:null, threshold:128, invert:false, vinyl:null, color:null, width:4, height:4, qty:1, shape:SHAPES[0], shipping:SHIPPING[0], address:{name:'',line1:'',line2:'',city:'',state:'',zip:'',country:''} };
const $ = (id) => document.getElementById(id);
const dropZone=$('dropZone'), fileInput=$('fileInput');
const mockCanvas=$('mockCanvas'), mockEmpty=$('mockEmpty'), ctx=mockCanvas.getContext('2d');
function buildVinyls(){ $('vinylGrid').innerHTML=VINYLS.map(v=>`<button data-vinyl="${v.id}" class="vinyl-card text-left panel rounded-xl p-3.5 relative border" style="background:var(--panel)"><i data-lucide="check-circle-2" class="check absolute top-3 right-3 w-4 h-4 text-[var(--accent)] opacity-0"></i><div class="w-9 h-9 rounded-lg bg-[var(--panel2)] grid place-items-center mb-2.5"><i data-lucide="${v.icon}" class="w-5 h-5 text-[var(--accent)]"></i></div><div class="font-semibold text-sm">${v.name} ${v.specialOrder?'<span class="ml-1 text-[10px] text-[var(--accent)]">SPECIAL ORDER</span>':''}</div><div class="text-[11px] text-[var(--sub)] mt-0.5">${v.desc}</div><div class="text-[11px] font-mono text-[var(--sub)] mt-2">$${v.price.toFixed(2)}/in²</div></button>`).join(''); $('vinylGrid').querySelectorAll('[data-vinyl]').forEach(btn=>btn.addEventListener('click',()=>selectVinyl(btn.dataset.vinyl))); }
function selectVinyl(id){ state.vinyl=VINYLS.find(v=>v.id===id); if(!state.vinyl)return; $('vinylGrid').querySelectorAll('[data-vinyl]').forEach(b=>b.classList.toggle('active',b.dataset.vinyl===id)); state.color=state.vinyl.colors[0]; const row=$('colorRow'),sw=$('colorSwatches'); if(state.vinyl.hasColor){row.classList.remove('hidden');sw.innerHTML=state.vinyl.colors.map(c=>`<button data-color="${c}" class="swatch w-9 h-9 rounded-full border-2" style="background:${c};border-color:var(--line)"></button>`).join('');sw.querySelectorAll('[data-color]').forEach(b=>b.addEventListener('click',()=>{state.color=b.dataset.color;sw.querySelectorAll('[data-color]').forEach(x=>x.style.borderColor='var(--line)');b.style.borderColor='var(--accent)';render()}));if(sw.querySelector('[data-color]'))sw.querySelector('[data-color]').style.borderColor='var(--accent)'}else{row.classList.add('hidden');state.color=state.vinyl.colors[0]} $('vinylTag').textContent=state.vinyl.name;render(); }
function buildShapes(){ $('shapeRow').innerHTML=SHAPES.map((s,i)=>`<button data-shape="${s.id}" class="tag px-3 py-2 rounded-lg text-sm ${i===0?'!border-[var(--accent)] text-[var(--ink)]':'text-[var(--sub)]'}">${s.name}</button>`).join('');$('shapeRow').querySelectorAll('[data-shape]').forEach(b=>b.addEventListener('click',()=>{state.shape=SHAPES.find(s=>s.id===b.dataset.shape);$('shapeRow').querySelectorAll('[data-shape]').forEach(x=>{x.classList.remove('!border-[var(--accent)]');x.classList.add('text-[var(--sub)]');x.classList.remove('text-[var(--ink)]')});b.classList.add('!border-[var(--accent)]','text-[var(--ink)]');b.classList.remove('text-[var(--sub)]');render()})); }
function buildShipping(){ $('shipRow').innerHTML=SHIPPING.map((s,i)=>`<button data-ship="${s.id}" class="ship-card text-left panel rounded-xl p-3.5 relative border ${i===0?'active':''}" style="background:var(--panel)"><i data-lucide="check-circle-2" class="scheck absolute top-3 right-3 w-4 h-4 text-[var(--accent)] ${i===0?'':'opacity-0'}"></i><div class="flex items-center gap-2 mb-1"><i data-lucide="${s.icon}" class="w-4 h-4 text-[var(--accent)]"></i><span class="font-semibold text-sm">${s.name}</span></div><div class="text-[11px] text-[var(--sub)]">${s.detail}</div><div class="text-[11px] font-mono mt-1.5 ${s.cost===0?'text-[var(--accent)]':'text-[var(--sub)]'}">${s.cost===0?'Free':'+$'+s.cost.toFixed(2)}</div></button>`).join('');$('shipRow').querySelectorAll('[data-ship]').forEach(btn=>btn.addEventListener('click',()=>{state.shipping=SHIPPING.find(s=>s.id===btn.dataset.ship);$('shipRow').querySelectorAll('[data-ship]').forEach(b=>{const on=b.dataset.ship===btn.dataset.ship;b.classList.toggle('active',on);b.querySelector('.scheck').classList.toggle('opacity-0',!on)});render()})); }
const ADDR_FIELDS={shName:'name',shLine1:'line1',shLine2:'line2',shCity:'city',shState:'state',shZip:'zip',shCountry:'country'};function bindAddress(){Object.entries(ADDR_FIELDS).forEach(([id,key])=>{const el=$(id);if(el)el.addEventListener('input',()=>{state.address[key]=el.value.trim();render()})})}function addressComplete(){const a=state.address;return a.name&&a.line1&&a.city&&a.state&&a.zip&&a.country}
dropZone.addEventListener('click',()=>fileInput.click());['dragover','dragenter'].forEach(e=>dropZone.addEventListener(e,ev=>{ev.preventDefault();dropZone.classList.add('border-[var(--accent)]')}));['dragleave','drop'].forEach(e=>dropZone.addEventListener(e,ev=>{ev.preventDefault();dropZone.classList.remove('border-[var(--accent)]')}));dropZone.addEventListener('drop',ev=>{const f=ev.dataTransfer.files[0];if(f)loadFile(f)});fileInput.addEventListener('change',e=>{const f=e.target.files[0];if(f)loadFile(f)});
function loadFile(f){if(!f.type.startsWith('image/')){alert('Please choose an image file.');return}state.file=f;state.imgName=f.name;const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{state.imageEl=img;$('imgControls').classList.remove('hidden');render();if(!state.vinyl)selectVinyl('glossy')};img.src=reader.result};reader.readAsDataURL(f)}
$('removeImg').addEventListener('click',()=>{state.imageEl=null;state.file=null;state.imgName=null;$('imgControls').classList.add('hidden');fileInput.value='';mockCanvas.classList.add('hidden');mockEmpty.classList.remove('hidden');render()});$('threshold').addEventListener('input',e=>{state.threshold=+e.target.value;$('threshVal').textContent=e.target.value;render()});$('invert').addEventListener('change',e=>{state.invert=e.target.checked;render()});$('width').addEventListener('input',e=>{state.width=+e.target.value;$('wVal').textContent=e.target.value;render()});$('height').addEventListener('input',e=>{state.height=+e.target.value;$('hVal').textContent=e.target.value;render()});$('qty').addEventListener('input',e=>{state.qty=+e.target.value;$('qVal').textContent=e.target.value;render()});
function render(){drawMock();updatePrice();const ready=state.imageEl&&state.vinyl&&signedIn&&addressComplete();$('purchaseBtn').disabled=!ready;const hint=$('purchaseHint');if(hint){let msg='';if(!signedIn)msg='Sign in to place your order.';else if(!state.imageEl)msg='Upload an image to continue.';else if(!state.vinyl)msg='Choose a vinyl type.';else if(!addressComplete())msg='Enter your shipping address to continue.';hint.textContent=msg;hint.classList.toggle('hidden',!msg)}}
function drawMock(){if(!state.imageEl){mockCanvas.classList.add('hidden');mockEmpty.classList.remove('hidden');return}mockEmpty.classList.add('hidden');mockCanvas.classList.remove('hidden');const S=600;mockCanvas.width=S;mockCanvas.height=S;ctx.clearRect(0,0,S,S);const img=state.imageEl,ratio=Math.min(S*.78/img.width,S*.78/img.height),w=img.width*ratio,h=img.height*ratio,ox=(S-w)/2,oy=(S-h)/2,off=document.createElement('canvas');off.width=Math.max(1,Math.round(w));off.height=Math.max(1,Math.round(h));const octx=off.getContext('2d');octx.drawImage(img,0,0,off.width,off.height);const data=octx.getImageData(0,0,off.width,off.height),d=data.data,vinylColor=pickInkColor(),rgb=hexToRgb(vinylColor);for(let i=0;i<d.length;i+=4){const a=d[i+3],lum=.299*d[i]+.587*d[i+1]+.114*d[i+2];let on=lum<state.threshold;if(state.invert)on=!on;if(a<40)on=false;if(on){d[i]=rgb.r;d[i+1]=rgb.g;d[i+2]=rgb.b;d[i+3]=255}else d[i+3]=0}octx.putImageData(data,0,0);ctx.save();applyShapeBacking(ox,oy,w,h);ctx.restore();ctx.drawImage(off,ox,oy,w,h);applyFinishEffect(off,ox,oy,w,h,vinylColor);applyWeedingLines(ox,oy,w,h,off)}
function pickInkColor(){if(!state.vinyl)return'#111111';if(state.vinyl.id==='glow'||state.vinyl.id==='hologlow')return'#7CFC00';if(state.vinyl.id==='holographic')return'#b98cff';if(state.vinyl.id==='holographic-black')return'#17131d';if(state.vinyl.id==='reflective-white')return'#FAFAFA';if(state.vinyl.id==='reflective-black')return'#111111';return state.color||'#111111'}
function applyShapeBacking(ox,oy,w,h){const pad=14,x=ox-pad,y=oy-pad,bw=w+pad*2,bh=h+pad*2;ctx.fillStyle='rgba(255,255,255,.06)';const sh=state.shape?.id;if(sh==='square')ctx.fillRect(x,y,bw,bh);else if(sh==='circle'){const r=Math.max(bw,bh)/2;ctx.beginPath();ctx.arc(ox+w/2,oy+h/2,r,0,7);ctx.fill()}else if(sh==='rounded'){roundRect(x,y,bw,bh,22);ctx.fill()}}
function applyFinishEffect(off,ox,oy,w,h,color){if(!state.vinyl)return;const id=state.vinyl.id;ctx.save();if(id==='glow'||id==='hologlow'){ctx.globalCompositeOperation='lighter';ctx.shadowColor='#7CFC00';ctx.shadowBlur=18;ctx.drawImage(off,ox,oy,w,h);ctx.shadowBlur=0}else if(id==='reflective'||id==='reflective-white'||id==='reflective-black'){ctx.globalAlpha=.25;ctx.globalCompositeOperation='screen';const g=ctx.createLinearGradient(ox,oy,ox+w,oy+h);g.addColorStop(0,'#fff');g.addColorStop(.5,'rgba(255,255,255,0)');g.addColorStop(1,'#fff');ctx.fillStyle=g;ctx.globalCompositeOperation='source-atop';ctx.fillRect(ox,oy,w,h)}else if(id==='holographic'||id==='holographic-black'){ctx.globalAlpha=.45;ctx.globalCompositeOperation='source-atop';const g=ctx.createLinearGradient(ox,oy,ox+w,oy+h);['#ff2d55','#ffcc00','#34c759','#00c7be','#5856d6','#ff2d55'].forEach((c,i,a)=>g.addColorStop(i/(a.length-1),c));ctx.fillStyle=g;ctx.fillRect(ox,oy,w,h)}else if(id==='chrome'){ctx.globalAlpha=.4;ctx.globalCompositeOperation='source-atop';const g=ctx.createLinearGradient(ox,oy,ox,oy+h);g.addColorStop(0,'#fff');g.addColorStop(.45,'rgba(255,255,255,0)');g.addColorStop(.55,'rgba(0,0,0,.25)');g.addColorStop(1,'#fff');ctx.fillStyle=g;ctx.fillRect(ox,oy,w,h)}else if(id==='glossy'){ctx.globalAlpha=.18;ctx.globalCompositeOperation='source-atop';const g=ctx.createLinearGradient(ox,oy,ox,oy+h*.5);g.addColorStop(0,'#fff');g.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=g;ctx.fillRect(ox,oy,w,h)}ctx.restore()}
function applyWeedingLines(ox,oy,w,h,decalOffscreenCanvas){const tempCanvas=document.createElement('canvas');tempCanvas.width=mockCanvas.width;tempCanvas.height=mockCanvas.height;const tCtx=tempCanvas.getContext('2d');tCtx.strokeStyle='#9ee7f7';tCtx.lineWidth=1;tCtx.beginPath();const gridSize=45;for(let x=ox;x<ox+w;x+=gridSize){tCtx.moveTo(x,oy);tCtx.lineTo(x,oy+h)}for(let y=oy;y<oy+h;y+=gridSize){tCtx.moveTo(ox,y);tCtx.lineTo(ox+w,y)}tCtx.rect(ox,oy,w,h);tCtx.stroke();tCtx.globalCompositeOperation='destination-out';tCtx.shadowColor='black';tCtx.shadowBlur=10;tCtx.drawImage(decalOffscreenCanvas,ox,oy,w,h);tCtx.drawImage(decalOffscreenCanvas,ox,oy,w,h);tCtx.drawImage(decalOffscreenCanvas,ox,oy,w,h);ctx.save();ctx.globalCompositeOperation='source-over';ctx.globalAlpha=.8;ctx.drawImage(tempCanvas,0,0);ctx.restore()}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}function hexToRgb(hex){hex=hex.replace('#','');if(hex.length===3)hex=hex.split('').map(c=>c+c).join('');const n=parseInt(hex,16);return{r:n>>16&255,g:n>>8&255,b:n&255}}
function computePrice(){if(!state.vinyl)return null;const area=state.width*state.height,shapeMult=state.shape?.mult??1,setup=3.5;let unit=Math.max(setup+area*state.vinyl.price*shapeMult,4);let disc=.02;const q=state.qty;if(q>=100)disc=.3;else if(q>=50)disc=.22;else if(q>=25)disc=.15;else if(q>=10)disc=.08;const unitDisc=unit*(1-disc),subtotal=unitDisc*q,ship=state.shipping?state.shipping.cost:0;return{area,unit,unitDisc,disc,subtotal,ship,total:subtotal+ship,shapeMult}}
function updatePrice(){const p=computePrice();if(!p){$('total').textContent='$0.00';return}$('pBase').textContent=state.vinyl.name+' · $'+state.vinyl.price.toFixed(2)+'/in²';$('pArea').textContent=`${state.width}"×${state.height}" (${p.area.toFixed(1)} in²)`;$('pQty').textContent='×'+state.qty;$('pDisc').textContent=p.disc>0?'−'+Math.round(p.disc*100)+'%':'None';$('pSubtotal').textContent='$'+p.subtotal.toFixed(2);$('pShip').textContent=p.ship>0?'$'+p.ship.toFixed(2):'Free';$('pShip').classList.toggle('text-[var(--accent)]',p.ship===0);$('unitPrice').textContent='$'+p.unitDisc.toFixed(2)+' / decal · '+(state.shipping?state.shipping.name:'');$('total').textContent='$'+p.total.toFixed(2)}
let signedIn=false,currentUser=null;async function refreshAuth(){if(!supabase){signedIn=false;currentUser=null}else{const{data:{user}}=await supabase.auth.getUser();currentUser=user;signedIn=!!user}$('authBtnText').textContent=signedIn?'Sign out':'Sign in';$('authStatus').textContent=signedIn?'Signed in as '+(currentUser.email||'customer'):'';$('authStatus').classList.toggle('hidden',!signedIn);render()}
const fluffCoven=$('fluffCoven');if(fluffCoven)fluffCoven.addEventListener('change',async()=>{if(!fluffCoven.checked)return;const email=currentUser?.email;if(!email){fluffCoven.checked=false;openModal('<p class="text-sm">Sign in first, then join Fluff Coven with the email on your account.</p>');return}fluffCoven.disabled=true;try{const response=await fetch('/api/fluff-signup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'Signup unavailable.');openModal('<p class="text-sm">You’re in. Welcome to Fluff Coven ✦</p>')}catch(error){fluffCoven.checked=false;openModal(`<p class="text-sm text-red-300">${String(error.message||'Signup unavailable.').replace(/[<>]/g,'')}</p>`)}finally{fluffCoven.disabled=false}});
$('authBtn').addEventListener('click',async()=>{if(!supabase){openModal('<p class="text-sm">Supabase is not configured yet.</p>');return}if(signedIn){await supabase.auth.signOut();await refreshAuth();return}const email=window.prompt('Enter your email for a secure sign-in link:');if(!email)return;const{error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.href}});if(error)openModal('<p class="text-sm text-red-300">'+error.message+'</p>');else openModal('<p class="text-sm">Check your email for a secure sign-in link.</p>')});if(supabase)supabase.auth.onAuthStateChange(()=>refreshAuth());
const modal=$('orderModal');function openModal(html){$('modalBody').innerHTML=html;modal.classList.remove('hidden');modal.classList.add('flex');createIcons({icons})}function closeModal(){modal.classList.add('hidden');modal.classList.remove('flex')}
$('purchaseBtn').addEventListener('click',onPurchase);async function onPurchase(){if(!state.imageEl||!state.vinyl)return;if(!signedIn){openModal('<p class="text-sm">Please sign in before placing your order.</p>');return}const p=computePrice();openModal('<div class="text-center"><div class="w-14 h-14 rounded-full bg-[var(--panel2)] grid place-items-center mx-auto mb-4"><i data-lucide="loader-2" class="w-7 h-7 text-[var(--accent)] animate-spin"></i></div><h3 class="display font-semibold text-lg">Opening secure checkout…</h3><p class="text-sm text-[var(--sub)] mt-1">Stripe will collect payment and shipping details securely.</p></div>');try{const response=await fetch('/api/create-checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({vinyl:state.vinyl.id,color:state.color,shape:state.shape.id,shipping:state.shipping.id,width:state.width,height:state.height,quantity:state.qty,artworkName:state.imgName,email:currentUser?.email||'',clientTotal:Math.round(p.total*100)})});const result=await response.json();if(!response.ok||!result.url)throw new Error(result.error||'Checkout is unavailable.');window.location.assign(result.url)}catch(err){openModal(`<div class="text-center"><div class="w-14 h-14 rounded-full bg-red-500/15 grid place-items-center mx-auto mb-4"><i data-lucide="alert-triangle" class="w-7 h-7 text-red-400"></i></div><h3 class="display font-semibold text-lg">Checkout could not open</h3><p class="text-sm text-[var(--sub)] mt-1">${String(err?.message||'Please try again.').replace(/[<>]/g,'')}</p><button onclick="document.getElementById('orderModal').classList.add('hidden')" class="mt-5 px-4 py-2 rounded-lg border border-[var(--line)] text-sm">Close</button></div>`);createIcons({icons})}}
function buildExportPng(){return Promise.resolve(null)}
init();async function init(){try{await loadCatalog();buildVinyls();buildShapes();buildShipping();bindAddress();updatePrice();await refreshAuth();createIcons({icons})}catch(error){console.error(error);$('vinylGrid').innerHTML='<p class="text-sm text-red-300">The vinyl catalog is temporarily unavailable. Please try again shortly.</p>'}}
